[project]
name = "autoencoder/general"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wiktor Jurkiewicz <watjurk@gmail.com>"]
channels = ["pytorch", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
pytorch = "2.1.1.*"
torchvision = "0.16.1.*"
torchaudio = "2.1.1.*"
matplotlib = "3.8.2.*"
numpy = "1.26.2.*"
polars = "0.19.19.*"
ipykernel = "6.26.0.*"
python = "3.11.6.*"
