[project]
name = "autoencoder/basic/sweep"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wiktor Jurkiewicz <watjurk@gmail.com>"]
channels = ["pytorch", "conda-forge"]
platforms = ["osx-arm64"]

[tasks]
create_sweep = "wandb sweep -e watjurk-vrije-team -p wiktor-vrije-learn.autoencoder.basic config.yaml"
start_agent = "wandb agent"

[dependencies]
pytorch = "2.1.1.*"
torchvision = "0.16.1.*"
numpy = "1.26.2.*"
python = "3.11.6.*"
fastprogress = "1.0.3.*"
wandb = ">=0.16.1,<0.17"
