[project]
name = "normal distibution"
version = "0.1.0"
description = "Add a short description here"
authors = ["Wiktor Jurkiewicz <watjurk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.0,<3.13"
matplotlib = ">=3.8.2,<3.9"
ipykernel = ">=6.26.0,<6.27"
ipywidgets = ">=8.1.1,<8.2"
